<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:sitemap="http://www.sitemaps.org/schemas/sitemap/0.9">
  <xsl:output method="html" indent="yes"/>
  <xsl:template match="/">
    <html>
      <head>
        <title>XML Sitemap - PNGTOSVG Converter</title>
        <meta charset="UTF-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
        <style>
          body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
            line-height: 1.6;
            margin: 0;
            padding: 2rem;
            background: #f8fafc;
            color: #334155;
          }
          .container {
            max-width: 1000px;
            margin: 0 auto;
            background: white;
            padding: 2rem;
            border-radius: 8px;
            box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.1);
          }
          h1 {
            color: #1e293b;
            font-size: 2rem;
            margin-bottom: 0.5rem;
            text-align: center;
          }
          .subtitle {
            text-align: center;
            color: #64748b;
            margin-bottom: 2rem;
            font-size: 1.1rem;
          }
          .url-list {
            list-style: none;
            padding: 0;
          }
          .url-item {
            background: #f8fafc;
            border: 1px solid #e2e8f0;
            border-radius: 6px;
            padding: 1rem;
            margin-bottom: 0.75rem;
            transition: all 0.2s ease;
          }
          .url-item:hover {
            border-color: #0ea5e9;
            box-shadow: 0 2px 4px rgba(14, 165, 233, 0.1);
          }
          .url-loc {
            font-weight: 600;
            color: #0ea5e9;
            text-decoration: none;
            font-size: 1.1rem;
            display: block;
            margin-bottom: 0.5rem;
          }
          .url-loc:hover {
            text-decoration: underline;
          }
          .url-meta {
            display: flex;
            gap: 1rem;
            font-size: 0.85rem;
            color: #64748b;
            flex-wrap: wrap;
          }
          .meta-item {
            background: white;
            padding: 0.25rem 0.5rem;
            border-radius: 4px;
            border: 1px solid #e2e8f0;
          }
          .priority-high { border-color: #22c55e; color: #16a34a; }
          .priority-medium { border-color: #f59e0b; color: #d97706; }
          .priority-low { border-color: #ef4444; color: #dc2626; }
          .footer {
            text-align: center;
            margin-top: 2rem;
            padding-top: 1rem;
            border-top: 1px solid #e2e8f0;
            color: #64748b;
            font-size: 0.9rem;
          }
          .stats {
            background: #f0f9ff;
            border: 1px solid #0ea5e9;
            border-radius: 6px;
            padding: 1rem;
            margin-bottom: 2rem;
            text-align: center;
          }
        </style>
      </head>
      <body>
        <div class="container">
          <h1>🗺️ XML Sitemap</h1>
          <p class="subtitle">PNGTOSVG Converter - Free Online PNG to SVG Tool</p>
          
          <div class="stats">
            <strong>Total URLs:</strong> <xsl:value-of select="count(//sitemap:url)"/> | 
            <strong>Last Updated:</strong> <xsl:value-of select="//sitemap:url[1]/sitemap:lastmod"/>
          </div>

          <ul class="url-list">
            <xsl:for-each select="//sitemap:url">
              <xsl:sort select="sitemap:priority" order="descending"/>
              <li class="url-item">
                <a href="{sitemap:loc}" class="url-loc" target="_blank">
                  <xsl:value-of select="sitemap:loc"/>
                </a>
                <div class="url-meta">
                  <span class="meta-item">
                    📅 <xsl:value-of select="sitemap:lastmod"/>
                  </span>
                  <span class="meta-item">
                    🔄 <xsl:value-of select="sitemap:changefreq"/>
                  </span>
                  <span>
                    <xsl:attribute name="class">
                      meta-item priority-
                      <xsl:choose>
                        <xsl:when test="sitemap:priority &gt;= 0.8">high</xsl:when>
                        <xsl:when test="sitemap:priority &gt;= 0.5">medium</xsl:when>
                        <xsl:otherwise>low</xsl:otherwise>
                      </xsl:choose>
                    </xsl:attribute>
                    ⭐ <xsl:value-of select="sitemap:priority"/>
                  </span>
                </div>
              </li>
            </xsl:for-each>
          </ul>

          <div class="footer">
            <p>Generated by PNGTOSVG Converter | 
            <a href="https://pngtosvgconverter.com" style="color: #0ea5e9;">Visit Website</a>
            </p>
            <p style="font-size: 0.8rem; margin-top: 0.5rem;">
              This sitemap contains <xsl:value-of select="count(//sitemap:url)"/> URLs for search engine crawling.
            </p>
          </div>
        </div>
      </body>
    </html>
  </xsl:template>
</xsl:stylesheet>
